name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v2
    - name: Build the Docker image
    - run: make build
    - with:
          file: ./docs/Dockerfile
          push: true

